---
title: "p8105_hw6_kq2127"
author: "Kristal Quispe"
date: "11/24/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(modelr)
library(mgcv)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
set.seed(1)
```

# Problem 1

Load and clean the data set
```{r}
bw_df =
  read_csv("./data/birthweight.csv") %>% 
  janitor::clean_names()%>% 
  mutate (
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace))
  
```


Fitting my model

```{r}
my_model = lm(bwt ~ fincome + gaweeks + blength, data = bw_df)
```


Plot of Model Residuals against fitted values 

```{r}
bw_df %>% 
  modelr::add_residuals(my_model) %>% 
  modelr::add_predictions(my_model) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()
```

Other models

```{r}
o1_model = lm(bwt ~ blength + gaweeks, data = bw_df)
o2_model = lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = bw_df)
```

Comparing other model

```{r}
cv_df = 
  crossv_mc(bw_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))
```

```{r}
cv_results = 
  cv_df %>% 
  mutate(
    my_mod = map(.x = train, ~lm(bwt ~ fincome + gaweeks + blength, data = .x)),
    o1_mod = map(.x = train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    o2_mod =  map(.x = train, ~lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * babysex + bhead * blength * babysex, data = .x)),
    rmse_mymod = map2_dbl(.x = my_mod, .y = test, ~rmse(.x, .y)),
    rmse_o1mod = map2_dbl(.x = o1_mod, .y = test, ~rmse(.x, .y)),
    rmse_o2mod = map2_dbl(.x = o2_mod, .y = test, ~rmse(.x, .y))
  )
```

Visualize the root mean square error for the models
```{r}
cv_results %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()
```

